### ISSUE TITLE
tvOS target is missing

### ISSUE THREAD

**Issue by muratakbal** [react-native-community/react-native-async-storage#108]
`tvOS` projects use `AsyncStorage` cannot be built. `libRNCAsycnStorage.a` doesn't have `tvOS` in its supported platforms. Also, there is no `tvOS` target exported separately.

## Expected behavior
`tvOS` projects should be able to use this library as before, like when it was part of `react-native`.

## Environment

- **Async Storage version**: `1.3.4`
- **React-Native version**: `0.59.8`
- **Platform tested**: `tvOS`
- **Logs/Error that are relevant**: 
```
no such file or directory: '/Users/muratakbal/Library/Developer/Xcode/DerivedData/hib-gjqyjyhlqffdzjcuyqvmniocngmq/Build/Products/Debug-appletvsimulator/libRNCAsyncStorage.a'
```

![Screen Shot 2019-05-20 at 12 12 33 PM](https://user-images.githubusercontent.com/1921705/58045864-98782700-7af8-11e9-8fce-62b4ae2d64be.png)

**Comment by Jeijie** [comment]
Hi,@Krizzu , I have still same problem  in version 1.4.1, after upgrated to version 1.5.0, but the issue remains unresolved.
![image](https://user-images.githubusercontent.com/9338052/60695095-0f377b00-9f13-11e9-90a2-e39722c23234.png)
![image](https://user-images.githubusercontent.com/9338052/60695099-15c5f280-9f13-11e9-92ad-007268c05085.png)
