### ISSUE TITLE
Not able to create iOS build

### ISSUE THREAD

**Issue by codoffer** [react-native-community/react-native-async-storage#112]
## Current behavior

I have delete node_modules and tried with fresh installation. Please help me for this.

node_modules/@react-native-community/async-storage/ios/RNCAsyncStorage.h:10:9: fatal error: 'RNCAsyncStorage/RNCAsyncStorageDelegate.h' file not found

info #import <RNCAsyncStorage/RNCAsyncStorageDelegate.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The following build commands failed:
	CompileC ...ios/build/testapp/Build/Intermediates.noindex/RNCAsyncStorage.build/Debug-iphonesimulator/RNCAsyncStorage.build/Objects-normal/x86_64/RNCAsyncStorage.o ...node_modules/@react-native-community/async-storage/ios/RNCAsyncStorage.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

## Repro steps

Getting below error on react-native run-ios command

## Environment

- **Async Storage version**: ^1.4.2
- **React-Native version**: 0.59.1
- **Platform tested**: iOS
- **Logs/Error that are relevant**:

**Comment by Krizzu** [comment]
Hey @codoffer, 

We have already issued for that (https://github.com/react-native-community/react-native-async-storage/issues/91)

There is a couple of suggestion of what to do in order to get it working. Please post in that issue for further help.

I'm going to close this one.

**Comment by tido64** [comment]
@codoffer Can you try the steps outlined here: https://github.com/react-native-community/react-native-async-storage/issues/86#issuecomment-489395351

The most important step is that you do `pod install` and `pod update RNCAsyncStorage` after every update. CocoaPods does not detect changes because it makes copies of the dependencies.

**Comment by codoffer** [comment]
@tido64 I have followed the steps and getting new error message.

/node_modules/@react-native-community/async-storage/ios/RNCAsyncStorage.h:8:9: 'React/RCTBridgeModule.h' file not found

**Comment by tido64** [comment]
For that particular issue, we'll try to help you in https://github.com/react-native-community/react-native-async-storage/issues/91 as @Krizzu forwarded you to. I'm going to close this issue now to avoid further forking.

Thanks
