### ISSUE TITLE
Create `useAsyncStorage` hook

### ISSUE THREAD

**Issue by michalchudziak** [react-native-community/react-native-async-storage#16]
What do you think of creating `useAsyncStore` hook, that encapsulates the most popular AsyncStorage methods?

```js
const [getItem, setItem] = useAsyncStorage('@NameOfTheStore')
```
Where `setItem(key, value)` would save the key in `@NameOfTheStore:${key}`, and `getItem(key)` would read from it.

It's just a thought 😅

**Comment by kadikraman** [comment]
It would probably have to return an object, since there are 4 possible operations on a single key.

```js
const { getItem, setItem, removeItem, mergeItem } = useAsyncStorage('@NameOfTheStore')
```

**Comment by kadikraman** [comment]
Hmm, just realised I didn't read your suggestion properly @michalchudziak - my implementation is for storing and retrieving a single value so the _benefit_ of using the hook would be that you don't need to always pass in the key. Whereas in your suggestion, the API would be _identical_ to the existing one, so it doesn't provide any benefit that I can see.

**Comment by msukmanowsky** [comment]
@michalchudziak I think this would accomplish what you were originally looking to do https://gist.github.com/msukmanowsky/08a3650223dda8b102d2c9fe94ad5c12

**Comment by TheDSCPL** [comment]
@msukmanowsky Kinda... That implementation only detects changes from within the same component's instance.

**Comment by msukmanowsky** [comment]
@TheDSCPL true, but that's usually handled by just using this at a top-level `App.js` and supplying the value to subcomponents via something like [`Context`](https://reactjs.org/docs/context.html).

**Comment by TheDSCPL** [comment]
Oh, yes! Nice! Imma do that :)

**Comment by wesson818** [comment]
@msukmanowsky It is great implementation of the useAsyncStorage custom hook. Works perfectly!
