### ISSUE TITLE
[General] Update Readme

### ISSUE THREAD

**Issue by Krizzu** [react-native-community/react-native-async-storage#2]
Update README to cover:

- Available API (Installation steps, linking)
- Example usages
- Contribution list

**Comment by Pushplaybang** [comment]
@Krizzu  - Readme could also use a "motivation" or "why".

I'm guessing that asyncStorage is not going to be part of core in the future?  couldn't see this in the RN docs, would be great to include a note about this.

**Comment by Krizzu** [comment]
Hey @Pushplaybang,

It's all part of [lean core effort for React Native.](https://github.com/facebook/react-native/issues/23313) I guess it'd be fine to add this info to readme.
