### ISSUE TITLE
Build error `RNCAsyncstorage.m` not found

### ISSUE THREAD

**Issue by sylvainbaronnet** [react-native-community/react-native-async-storage#23]
Hi,

Edit: with version `1.0.2`

There's a typo in `RNCAsyncStorage.m` filename, which is `RNCAsyncstorage.m` in build (notice the S of Storage)

`error: Build input file cannot be found: '/Users/.../node_modules/@react-native-community/async-storage/ios/RNCAsyncstorage.m'`

I tried to rename the file and it works

**Comment by sylvainbaronnet** [comment]
My HD is `APFS (Case-sensitive)` so it might be the reason (maybe it works on Case-insensitive HD ?)

**Comment by Krizzu** [comment]
Thanks for reporting this.
I just initialized repo and tested Async Storage `1.0.2` from npm. Everything works.
But it's worth to fix it, to avoid issues in the future.

Do you mind opening PR with changes?

Thanks.

**Comment by sylvainbaronnet** [comment]
Sure, just renaming the file works for you ?

**Comment by Krizzu** [comment]
I'd like to keep filename in camel case. Changing occurrences of `Asyncstorage` into `AsyncStorage` will do the job.

Also, to confirm everything works, after you apply changes, you can unlink `AsyncStorage` from example project and link it back manually, to see if it builds/works normally.

Thanks.

**Comment by sylvainbaronnet** [comment]
see : https://github.com/react-native-community/react-native-async-storage/pull/26

**Comment by Krizzu** [comment]
Closing with #26 merged
