### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by jeffreyffs** [react-native-community/react-native-async-storage#27]
The types exist here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/42e3741a35ebe4b181ea80089ee960fc7fb9ae59/types/react-native/index.d.ts#L6987

(except for the new `useAsyncStorage` function)

They will need to be copied out to a separate folder (react-native-community__async-storage)

**Comment by Krizzu** [comment]
Sounds good, it'd be great to have ts typings onboard.
