### ISSUE TITLE
Allow brownfield apps to handle requests

### ISSUE THREAD

**Issue by tido64** [react-native-community/react-native-async-storage#33]
## Motivation

We have brownfield apps with existing storage solutions that we want our React Native components to take advantage of. For example, one of our apps use [PINCache](https://github.com/pinterest/PINCache) to control lifetime of the stored data and the size of the disk cache.

## Description

Before I start implementing on this, I'd like to run you by my solution and get some feedback on whether I'm on the correct path.

In `RNCAsyncStorage`, we add a delegate `@property`, e.g.:

```objc
@property (nonatomic, weak, nullable) id<RNCAsyncStorageDelegate> delegate;
```

For every `RCT_EXPORT_METHOD`, we call the delegate if it's set, otherwise we do the normal operations.

Consumers can then set the delegate like so:

```objc
RNCAsyncStorage *asyncStorage = [bridge moduleForClass:[RNCAsyncStorage class]];
asyncStorage.delegate = self;
```

Let me know what you think.

Thanks.

**Comment by Krizzu** [comment]
Hey @tido64 	
So, if I understood correctly, you want to expand AS capabilities, by attaching delegates to external storage solutions?

I like the idea. I was thinking about a way to make Async Storage extendable - by applying adapters for external storages.

Are you planning on including this feature in Android too?

**Comment by tido64** [comment]
Yes, that's correct. I haven't looked at the Android implementation yet but we do need it, so I will look at it next when I have time.

**Comment by tido64** [comment]
Merged. Thanks, @Krizzu 🎉
