### ISSUE TITLE
null is not an object(evaluating 'RCTAsyncStorage.multiMerge')

### ISSUE THREAD

**Issue by featherzwj** [react-native-community/react-native-async-storage#42]
## Current behavior

null is not an object(evaluating 'RCTAsyncStorage.multiMerge')

## Expected behavior

 
![image](https://user-images.githubusercontent.com/26322082/54655950-c2b06700-4afe-11e9-911b-838fae24c763.png)

## Environment

- **Async Storage version**: 
- **React-Native version**: react-native 0.59.0
-**Platform tested**:   Android

**Comment by featherzwj** [comment]
sorry, i just found out after downloading the installation package ,  i forgot  to run-android again.

**Comment by Krizzu** [comment]
Hey @featherzwj,

Glad you have it working now. :)
