### ISSUE TITLE
Setting this.props into Async

### ISSUE THREAD

**Issue by velcis** [react-native-community/react-native-async-storage#45]
I can't set this.state.user inside AsyncStorage.setItem() on the latest RN version, now with this package i can't use it. It shows warning message... Line Column sourceURL.

**Comment by Krizzu** [comment]
Hey @velcis 	
Can you provide some more context of how you're trying to do it?


Thanks.

**Comment by Krizzu** [comment]
Closing for now, let me know if you need more help, so we can reopen it.
