### ISSUE TITLE
@react-native-community_async-storage:verifyReleaseResources FAILED

### ISSUE THREAD

**Issue by Proxy08** [react-native-community/react-native-async-storage#49]
Hey, Whenever I run ```./gradlew assembleRelease``` I got this error:
```
Execution failed for task ':@react-native-community_async-storage:verifyReleaseResources'.
java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/darkkingmarvel/Desktop/Jiffeo/v2/jiffeoApp/node_modules/@react-native-community/async-storage/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/darkkingmarvel/Desktop/Jiffeo/v2/jiffeoApp/node_modules/@react-native-community/async-storage/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/darkkingmarvel/Desktop/Jiffeo/v2/jiffeoApp/node_modules/@react-native-community/async-storage/android/build/intermediates/res/merged/release/values/values.xml:2714: error: resource android:attr/fontVariationSettings not found.
  /Users/darkkingmarvel/Desktop/Jiffeo/v2/jiffeoApp/node_modules/@react-native-community/async-storage/android/build/intermediates/res/merged/release/values/values.xml:2715: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
```

- **Async Storage version**:1.2.2
- **React-Native version**: 0.59.2
- **Platform tested**:  Android

**Comment by Krizzu** [comment]
Hey @Proxy08 	

What's your `compileSdkVersion` for your app?

**Comment by Proxy08** [comment]
here @Krizzu 
```
        buildToolsVersion = "27.0.3"
        minSdkVersion = 19
        compileSdkVersion = 27
        targetSdkVersion = 27
        supportLibVersion = "27.1.1"
```

**Comment by IjzerenHein** [comment]
Have you tried cleaning the Android build with `/gradlew clean` in the `android` folder? That fixed the problem for me.

**Comment by Krizzu** [comment]
@Proxy08 	

Have you tried to bump `compileSdkVersion` to 28?

**Comment by manelsanz** [comment]
Hi, I have the same problem with `compileSdkVersion =28.0.3` and previous made `./gradlew clean`

```
> Task :@react-native-community_async-storage:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@react-native-community_async-storage:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  PATH_PROJECT\node_modules\@react-native-community\async-storage\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  PATH_PROJECT\node_modules\@react-native-community\async-storage\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  PATH_PROJECT\node_modules\@react-native-community\async-storage\android\build\intermediates\res\merged\release\values\values.xml:2714: error: resource android:attr/fontVariationSettings not found.
  PATH_PROJECT\node_modules\@react-native-community\async-storage\android\build\intermediates\res\merged\release\values\values.xml:2715: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
```

**Comment by manelsanz** [comment]
Finally, I solved it.
Steps:
- My Yarn version was `1.12.1`, so was mandatory update it. Now I have 1.15.2
- Remove `node_modules` and reinstall it using `yarn install` / `npm install`
- Put this code on android/app/build.gradle:
```
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28     //do this in android/app/build.gradle too
                buildToolsVersion '28.0.3'  //do this in android/app/build.gradle too
                variantFilter { variant ->
                    def names = variant.flavors*.name
                    // To check for a certain build type, use variant.buildType.name == "<buildType>"
                    if (names.contains("reactNative51") || names.contains("reactNative55") || names.contains("reactNative56")) {
                        // Gradle ignores any variants that satisfy the conditions above.
                        setIgnore(true)
                    }
                }
            }
        }
    }
}
```

Now ./gradlew assembleRelease works!

PD: don't forgive place the keystore file to android/app ;)

**Comment by Krizzu** [comment]
Hey @manelsanz, sorry for not getting back to you earlier.

I'm glad you got it working for you. By default, Async Storage [picks compile/target SDK version from your root `build.gradle`, fallbacking to v28 when not successful.](https://github.com/react-native-community/react-native-async-storage/blob/master/android/build.gradle#L24-L25). I believe this was not somehow picked up in your project, maybe because of the setup.

Anyway, I'm closing this for now, feel free to reopen once it's needed again.


thanks.

**Comment by aliazizi** [comment]
I have same problem, I just say it maybe helpfull for someone
`/gradlew clean` and put sdk version to 28 is working,
I have this problem after update,
Thanks @Krizzu

**Comment by gre-dev** [comment]
Solved for me @manelsanz , Thanks

**Comment by shayelbaz1** [comment]
This is my error @manelsanz 
`
> Task :react-native-async-storage_async-storage:verifyReleaseResources FAILED
aapt2 W 05-19 02:13:35 33622 4202863 LoadedArsc.cpp:657] Unknown chunk type '200'.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-async-storage_async-storage:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     AAPT: aapt2 W 05-19 02:13:34 33623 4202866 LoadedArsc.cpp:657] Unknown chunk type '200'.
     /Users/user/ls-techs/community-application/node_modules/@react-native-async-storage/async-storage/android/build/intermediates/res/merged/release/layout/autofill_inline_suggestion.xml:18: error: resource attr/autofillInlineSuggestionChip (aka com.reactnativecommunity.asyncstorage:attr/autofillInlineSuggestionChip) not found.
     /Users/user/ls-techs/community-application/node_modules/@react-native-async-storage/async-storage/android/build/intermediates/res/merged/release/layout/autofill_inline_suggestion.xml:25: error: resource attr/autofillInlineSuggestionStartIconStyle (aka com.reactnativecommunity.asyncstorage:attr/autofillInlineSuggestionStartIconStyle) not found.
     /Users/user/ls-techs/community-application/node_modules/@react-native-async-storage/async-storage/android/build/intermediates/res/merged/release/layout/autofill_inline_suggestion.xml:32: error: resource attr/autofillInlineSuggestionTitle (aka com.reactnativecommunity.asyncstorage:attr/autofillInlineSuggestionTitle) not found.
     /Users/user/ls-techs/community-application/node_modules/@react-native-async-storage/async-storage/android/build/intermediates/res/merged/release/layout/autofill_inline_suggestion.xml:41: error: resource attr/autofillInlineSuggestionSubtitle (aka com.reactnativecommunity.asyncstorage:attr/autofillInlineSuggestionSubtitle) not found.
     /Users/user/ls-techs/community-application/node_modules/@react-native-async-storage/async-storage/android/build/intermediates/res/merged/release/layout/autofill_inline_suggestion.xml:50: error: resource attr/autofillInlineSuggestionEndIconStyle (aka com.reactnativecommunity.asyncstorage:attr/autofillInlineSuggestionEndIconStyle) not found.
     error: failed linking file resources.
`

and your solution not helped me...

ANY HELP HERE?
