### ISSUE TITLE
When to use flushGetRequests?

### ISSUE THREAD

**Issue by mangei** [react-native-community/react-native-async-storage#50]
## You want to:  
When to use `flushGetRequests`?

## Details:
I posted this question also an StackOverflow, but still did not get any answer.
https://stackoverflow.com/questions/52526121/when-to-use-flushgetrequests-in-asyncstorage-in-react-native

I integrated it into my own get function, since I had sometimes the problem, that the function did not complete. Still, this way of doing it, does not feel right to me:  
```
getItem(key) {
    let resultPromise = AsyncStorage.getItem(PREFIX + key);
    AsyncStorage.flushGetRequests();
    return resultPromise.catch(() => null);
}
```

Please clarify. Thank you!

 ~ Manuel

**Comment by Krizzu** [comment]
Hey @mangei, sorry for getting back to you so late!

I'm afraid I don't know exact thought behind design process here, but let me try.

I believe `flushGetRequest` was implemented to optimize native calls for data, specifically when using callbacks. 
Like we know, accessing external resources (like DB, reading files) can be "expensive", so devs behind Async Storage tried to make it as performant as possible.

From the implementation, you can notice that user-facing `.multiGet` method is not actually calling `.multiGet` on native side directly. Besides collecting the request and storing it internally (also, removing dup keys on the way), it checks if `this._immediate` is already set.

If it's set, then it just proceed with storing keys/requests.

if it's not set, it fires a `setImmediate` with `flushGetRequests` call.


[From React Native docs](https://facebook.github.io/react-native/docs/timers) you can read that 
> setImmediate is executed at the end of the current JavaScript execution block, right before sending the batched response back to native.

What it means that `flushGetRequests` will be called when the method calling it will finish executing.

For example:


```javascript
getData() {
    AsyncStorage.multiGet(['k1', 'k2'], () => console.log('done'))
}
```

`flushGetRequests` is called after `getData` has finished executing.

Where is the optimization, you may ask.
What if `getData` had multiple calls to `multiGet`?

```javascript
getData() {
    AsyncStorage.multiGet(['k1', 'k2'], () => console.log('done'))
    AsyncStorage.multiGet(['k3', 'k4'], () => console.log('done1'))
    AsyncStorage.multiGet(['k5', 'k6'], () => console.log('done2'))
}
```

Calling DB/File system every time would be highly inefficient here. So instead, `.multiGet` gathers all this information and sends it to the native side once this execution is `getData`, in a single call. 

You don't have to call `flushGetRequests` yourself - unless you're calling multiple `getItem`/`multiGet` sequentially, not asynchronously (using promises), where you need result from one call to make another (one is based on previous one).

I hope this somehow gets you the answer you're looking for.


thanks.

**Comment by mangei** [comment]
@Krizzu thank you very much! now it's much clearer to me. probably the documentation should get an update ;)
