### ISSUE TITLE
Linking when using kotlin not possible? NativeModule.RCTAsyncStorage is null.

### ISSUE THREAD

**Issue by rpuls** [react-native-community/react-native-async-storage#51]
## You want to:  
Since I was getting warnings that the react-native asyncStorags is becomming deprecated and is moved (here) to individual package, I decided to install... This seems to be a pain in the a** every time, was also troubleful when I installed RCs' extracted WebView. (grumpy sorry)....

Anyway, this time I am stuck with failing jest tests that I have not been able to resolve after 24 hours of trying. Have had multiple colleges passing by as well as asked for help on SO.
Please check this link for further issue despription: https://stackoverflow.com/questions/55418910/jest-test-fails-after-installing-react-native-async-storage

I did manual linking since `react-native link` will not work for this module as MainApplication.java does not exist when using kotlin. Instead I have MainApplication.kt

After linking manually the async functions are working just fine. Except the jest test are unable to find the module. 
` @RNCommunity/AsyncStorage: NativeModule.RCTAsyncStorage is null.`

Any suggestions?

**Comment by tbergq** [comment]
Hi, I answered your post on stackoverflow. 

Also see [our repo](https://github.com/kiwicom/mobile/blob/master/app/core/config/NativeModulesMocks/AsyncStorage.js) if you like.

**Comment by Krizzu** [comment]
@rpuls 	Hey, thanks for reaching out.

I'm on the way of writing mocks to be used with Jest. I'm aiming to finish in few days, alongside with docs explaining how to test it.

For now, to get by this error, you'd have to mock `NativeModule` from `react-native`, to return [either of those modules](https://github.com/react-native-community/react-native-async-storage/blob/master/lib/AsyncStorage.js#L17).

**Comment by rpuls** [comment]
@Krizzu 
> I'm on the way of writing mocks to be used with Jest. I'm aiming to finish in few days, alongside with docs explaining how to test it.
> 
> For now, to get by this error, you'd have to mock `NativeModule` from `react-native`, to return [either of those modules](https://github.com/react-native-community/react-native-async-storage/blob/master/lib/AsyncStorage.js#L17).

Hey thanks for replying! I found a solution that worked. Tried many different ways of mocking the AsyncStorage. 4th attempt worked like a charm. I updated my stackoverflow with the solution https://stackoverflow.com/questions/55418910/jest-test-fails-after-installing-react-native-async-storage/55421364?noredirect=1#comment97619261_55421364

**Comment by Krizzu** [comment]
Hey @rpuls,

I've created https://github.com/react-native-community/react-native-async-storage/pull/53, so future cases with Jest testing will be easier.


thanks.

**Comment by Krizzu** [comment]
v1.3.0 released, please check it out 🙏
