### ISSUE TITLE
AsyncStorage iOS not Work RN V0.59.2

### ISSUE THREAD

**Issue by cristianmgb** [react-native-community/react-native-async-storage#56]
## Details

![Simulator Screen Shot - iPhone X - 2019-04-03 at 17 22 34](https://user-images.githubusercontent.com/4694439/55517250-6ccadb80-5635-11e9-878f-df52b3a06ddc.png)

**Comment by Krizzu** [comment]
Hey @cristianmgb ,

Did you follow the points listen in the red screen?

**Comment by cristianmgb** [comment]
yes, i did. And didn`t work out. but the problem is only in IOS because in android works perfectly. 
 i`m using the version RN 0.59.2.

**Comment by Krizzu** [comment]
@cristianmgb 
This error comes from the fact that Async Storage is not linked, and if linked, you'd need to rebuild native part.

Try this:
- Stop packager
- Run `react-native link @react-native-community/async-storage` once again, to make sure it's linked (no errors, just message saying it's already done)
- run `react-native run-ios` to get fresh build
- run the packager with `--clearCache` flag


Let me know how did it go.

**Comment by cristianmgb** [comment]
i follow all the steps and still not work. 
i created  a new project whit all the step you give me and still not work. 

<img width="832" alt="Captura de Pantalla 2019-04-04 a la(s) 3 16 31 p  m" src="https://user-images.githubusercontent.com/4694439/55585591-a90d4300-56ec-11e9-8662-96e7c4798ee3.png">
![Simulator Screen Shot - iPhone X - 2019-04-04 at 15 17 11](https://user-images.githubusercontent.com/4694439/55585631-bcb8a980-56ec-11e9-88fe-9ef2140209cd.png)

**Comment by Sam-Hoult** [comment]
@cristianmgb I just hit this same issue. The guide is missing the rather important point of `react-native link` then `cd ios` `pod install`.

Inside your xCode you should see:
![image](https://user-images.githubusercontent.com/1436841/55589894-5df03180-56e6-11e9-99fb-2ce51e83b3fb.png)

Hope this helps

**Comment by cristianmgb** [comment]
> @cristianmgb I just hit this same issue. The guide is missing the rather important point of `react-native link` then `cd ios` `pod install`.
> 
> Inside your xCode you should see:
> ![image](https://user-images.githubusercontent.com/1436841/55589894-5df03180-56e6-11e9-99fb-2ce51e83b3fb.png)
> 
> Hope this helps

<img width="258" alt="Captura de Pantalla 2019-04-04 a la(s) 4 54 29 p  m" src="https://user-images.githubusercontent.com/4694439/55591136-60f51d00-56fa-11e9-8798-25c19c0822f3.png">

the issues continues.

**Comment by Sam-Hoult** [comment]
@cristianmgb Hmm. I think my podfile already accounts for that madness from AppCenter doing the same to me:
```
target 'RN_app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  platform :ios, '9.0'
 
  pod 'AppCenter/Crashes', '~> 1.14.0'
  pod 'AppCenter/Analytics', '~> 1.14.0'
  pod 'AppCenterReactNativeShared', '~> 1.13.0'

  node_modules_path = '../node_modules'

  pod 'yoga', path: "#{node_modules_path}/react-native/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: "#{node_modules_path}/react-native"

  pod 'ReactNativeSocketMobile', path: "#{node_modules_path}/@getgreenline/react-native-socket-mobile/ios"

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'

  pod 'react-native-async-storage', :path => '../node_modules/@react-native-community/async-storage'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

**Comment by clucasalcantara** [comment]
Also having this issue here, followed every step several times.

**Comment by QShengW** [comment]
I have the same problem

**Comment by Krizzu** [comment]
Hey,

Are you using `pods` by any chance?

**Comment by cristianmgb** [comment]
> Hey,
> 
> Are you using `pods` by any chance?

<img width="832" alt="Captura de Pantalla 2019-04-04 a la(s) 3 16 31 p  m" src="https://user-images.githubusercontent.com/4694439/55650962-cacdff00-57ac-11e9-9da9-854c2ccdb3c0.png">

This is my pod file.

**Comment by cristianmgb** [comment]
<img width="1540" alt="Captura de Pantalla 2019-04-05 a la(s) 2 18 08 p  m" src="https://user-images.githubusercontent.com/4694439/55651282-b2aaaf80-57ad-11e9-8a77-6a32a3b7490a.png">

**Comment by Krizzu** [comment]
I've initialized a new RN project (RN 0.59.1) to test it out. I was able to successfully link and run the app (with and without pods).

Here're the steps I did:

1. Init project
2. Add `@react-native-community/async-storage` via `yarn add`
3. Go to `ios/`, `pod init`
4. My `Podfile`, before linking:

```ruby
target 'YOUR_PROJECT_NAME_HERE' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  platform :ios, '9.0'


  node_modules_path = '../node_modules'

  pod 'yoga', path: "#{node_modules_path}/react-native/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: "#{node_modules_path}/react-native"

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

5. Run `react-native link @react-native-community/async-storage` in root directory
Command adds a line in `Podfile`, just below `pod 'React'`:

```ruby
  pod 'react-native-async-storage', :path => '../node_modules/@react-native-community/async-storage'`
```

7. Run `pod install` in `ios/`
8. Open `ios/ProjectName.xcworkspace` (mind **.xcworkspace** extension) and press `run` OR run `react-native run-ios` in root


If anyone still have some issues, before you post that you got the same problem - please provide some more info/repro steps.
Please check if problem exists for you if in a new RN app - it might mean that you're missing some steps, like pod installing, in your original project.


thanks.

**Comment by cristianmgb** [comment]
> I've initialized a new RN project (RN 0.59.1) to test it out. I was able to successfully link and run the app (with and without pods).
> 
> Here're the steps I did:
> 
> 1. Init project
> 2. Add `@react-native-community/async-storage` via `yarn add`
> 3. Go to `ios/`, `pod init`
> 4. My `Podfile`, before linking:
> 
> ```ruby
> target 'YOUR_PROJECT_NAME_HERE' do
>   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
>   # use_frameworks!
>   platform :ios, '9.0'
> 
> 
>   node_modules_path = '../node_modules'
> 
>   pod 'yoga', path: "#{node_modules_path}/react-native/ReactCommon/yoga/yoga.podspec"
>   pod 'React', path: "#{node_modules_path}/react-native"
> 
> end
> 
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     if target.name == "React"
>       target.remove_from_project
>     end
>   end
> end
> ```
> 
> 1. Run `react-native link @react-native-community/async-storage` in root directory
>    Command adds a line in `Podfile`, just below `pod 'React'`:
> 
> ```ruby
>   pod 'react-native-async-storage', :path => '../node_modules/@react-native-community/async-storage'`
> ```
> 
> 1. Run `pod install` in `ios/`
> 2. Open `ios/ProjectName.xcworkspace` (mind **.xcworkspace** extension) and press `run` OR run `react-native run-ios` in root
> 
> If anyone still have some issues, before you post that you got the same problem - please provide some more info/repro steps.
> Please check if problem exists for you if in a new RN app - it might mean that you're missing some steps, like pod installing, in your original project.
> 
> thanks.

work for me. 👍

**Comment by Krizzu** [comment]
We've updated the docs. Closing this for now.


thanks.
