### ISSUE TITLE
multiGet can return nulls, but the TS types do not reflect this

### ISSUE THREAD

**Issue by lukewlms** [react-native-community/react-native-async-storage#58]
## Current behavior

Querying AsyncStorage for an unknown key using multiGet can return null values.

However [the types indicate this is impossible](https://github.com/react-native-community/react-native-async-storage/blob/master/types/index.d.ts#L55).

## Expected behavior

Types should indicate that returning null is possible, OR null should never be returned (I don't know which is correct, but I would think the types).

## Repro steps

Run code:
```ts
  const [testPair] = await AsyncStorage.multiGet(["DOES NOT EXIST"]);
  console.log(testPair);
```

return value: ["DOES NOT EXIST", null]

## Environment

- **Async Storage version**: Latest

"@react-native-community/async-storage": "^1.2.2",

"react-native": "0.59.1",
- **Platform tested**: iOS

**Comment by Krizzu** [comment]
Hey @lukewlms, thanks for reporting this.

Yes, it seems it slipped through by mistake - obviously, AS can return `null` if something does not exist.

I'd suggest to update the types. Mind opening a PR?


thanks.

**Comment by lukewlms** [comment]
Created https://github.com/react-native-community/react-native-async-storage/pull/59

**Comment by Krizzu** [comment]
Merged,


thanks.
