### ISSUE TITLE
Xcode archive generates Generic Xcode Archive instead of IPA

### ISSUE THREAD

**Issue by mohammadalijf** [react-native-community/react-native-async-storage#76]
## Current behavior

after updating to 1.3.1 Xcode creates Generic Xcode Archive instead of creating IPA. after looking up the problem and checking created archive, i found out `RNCAsyncStorage.h` and `RNCAsyncStorageDelegate.h` which are header files for the library is included in archive. you can find headers in 
Archive.xcarchive -> show Package Content/Products/usr/local/include

after looking up the problem i found a solution [here](https://stackoverflow.com/a/48408047/2161945) which is to move headers from Public to Project in the Build Phase / Headers.

## Expected behavior

Xcode should create IPA not a Generic Xcode Archive 

## Repro steps

- Xcode -> Clean
- Xcode -> clean DerivedData folder
- Xcode -> Archive

## Environment

- **Async Storage version**: 1.3.1
- **React-Native version**: 0.59.4
- **Platform tested**: iOS

**Comment by tido64** [comment]
Thanks for the report! The fix was merged and released with v1.3.3. Please upgrade and let us know if you hit any other issues. 😄
