### ISSUE TITLE
Document semantics

### ISSUE THREAD

**Issue by xaviershay** [react-native-community/react-native-async-storage#85]
This is a documentation request. It's not clear to me the intended semantics of this library.

If `setItem` promise resolves, does that indicate that a subsequent `getItem` will return the latest value? Or that it will be eventually consistent?

If it fails, is the state of the store the old value, or undefined?

For `setMultiple`, is it atomic?

etc...

Thanks!

**Comment by Krizzu** [comment]
Hey @xaviershay,

Thanks for suggestion, I guess it'd be great to have such info. Would you like to give it a go?


thanks.

**Comment by xaviershay** [comment]
I don't know what the intent is :) if you give me a sketch of an answer, I'll happily clean it up and send a pr for the docs.

**Comment by Krizzu** [comment]
@xaviershay ,

That'd involve going into the source code and filling up [the docs](https://github.com/react-native-community/react-native-async-storage/blob/master/docs/API.md) with semantic information you mentioned. We do it partially, but could definitely be done better.


thanks.

**Comment by xaviershay** [comment]
ok, I'm extremely new to react-native, and in particular don't quite understand how native modules work / the bridge yet. I can revisit once I've learned some more.

**Comment by Krizzu** [comment]
Right, so I'm closing this one for now, let me know when should we re-open it.


thanks.
