### ISSUE TITLE
iOS Headers should be added at project level not public level

### ISSUE THREAD

**Issue by reilem** [react-native-community/react-native-async-storage#87]
## Current behavior

When manually linking the library, archiving will fail due to headers not being added to project level. With will cause the app to be bundled as a Generic XCode project instead of an iOS App.

## Expected behavior

The app to be bundled as an iOS App.

## Repro steps

Create a new react-native project and manually link AsyncStorage. Attempt to Archive. In the Organiser window you will see the new Archive listed under "Other" instead of under iOS Apps.

## Solution

<img width="1034" alt="Screenshot 2019-04-20 at 13 30 42" src="https://user-images.githubusercontent.com/11155505/56456761-25508900-6371-11e9-89c9-6f673e9a2724.png">
<img width="931" alt="Screenshot 2019-04-20 at 13 30 47" src="https://user-images.githubusercontent.com/11155505/56456762-27b2e300-6371-11e9-8f07-716d79b27b3b.png">

**Comment by reilem** [comment]
Oh nevermind, I think this has been fixed in the latest release?

**Comment by Krizzu** [comment]
@reilem Hey,

Yup, fixed in v1.3.3 🙏
