### ISSUE TITLE
Is the Readme not supposed to mention 'unencrypted'?

### ISSUE THREAD

**Issue by bart-kneepkens** [react-native-community/react-native-async-storage#90]
## You want to:  
When async-storage was included in react-native, the page mentioned that it was unencrypted (https://facebook.github.io/react-native/docs/asyncstorage). Is that not the case anymore?

**Comment by Krizzu** [comment]
Hey @bart-kneepkens 

Yeah, that's missing from the description. Mind bringing it back?


thanks.

**Comment by pbitkowski** [comment]
Done by #100

**Comment by tido64** [comment]
Thanks for fixing this. I'm closing this issue since it's merged now.
