### ISSUE TITLE
Incorrect podspec's git tag

### ISSUE THREAD

**Issue by happy-thorny** [react-native-community/react-native-async-storage#92]
## Current behavior

`pod install` causes an error (at least when installing AsyncStorage manually): `Could not find remote branch 1.2.1 to clone`. 

## Expected behavior

No error occurs.

## Repro steps

1. Create new empty RN project with iOS project based on Cocoapods
1. Add `"@react-native-community/async-storage": "^1.2.1"` to package.json dependencies
1. `npm install`
1. Add `pod 'react-native-async-storage', :podspec => '../node_modules/@react-native-community/async-storage'` to Podfile
1. `pod install`

## Environment

- **Async Storage version**: 1.2.1
- **React-Native version**: 0.59.1
- **Platform tested**: iOS (the issue is not applicable to Android)
- **Logs/Error that are relevant**: 
```
[!] Error installing react-native-async-storage
[!] /usr/bin/git clone https://github.com/react-native-community/react-native-async-storage.git /var/folders/... --template= --single-branch --depth 1 --branch 1.2.1

Cloning into '/var/folders/...'...
warning: Could not find remote branch 1.2.1 to clone.
```

**Comment by Krizzu** [comment]
@happy-thorny Thanks a lot for raising that! Your PR with fix is merged. Should be out soon.


thanks.
