### ISSUE TITLE
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by anubhavnandan** [react-native-community/react-native-async-storage#97]
how to resolve above error, I got this while running the app. `react-native run-android`

**Comment by anubhavnandan** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':@react-native-community_async-storage'.
> Could not resolve all artifacts for configuration ':@react-native-community_async-storage:classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-reflect:1.2.0.

     Required by:
         project :@react-native-community_async-storage > com.android.tools.build:gradle:3.2.1 > com.android.tools.lint:lint-gradle-api:26.2.1
         project :@react-native-community_async-storage > com.android.tools.build:gradle:3.2.1 > com.android.tools.build:builder:3.2.1 > com.android.tools:sdk-common:26.2.1
      > Could not resolve org.jetbrains.kotlin:kotlin-reflect:1.2.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-reflect/1.2.0/kotlin-reflect-1.2.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-reflect/1.2.0/kotlin-reflect-1.2.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve org.jetbrains.kotlin:kotlin-reflect:1.2.0.
         > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.2.0/kotlin-reflect-1.2.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.2.0/kotlin-reflect-1.2.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.2.71.
     Required by:
         project :@react-native-community_async-storage > com.android.tools.build:gradle:3.2.1 > org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71
         project :@react-native-community_async-storage > com.android.tools.build:gradle:3.2.1 > org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71 > org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.71
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.2.71.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.2.71.
         > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.2.71.
     Required by:
         project :@react-native-community_async-storage > com.android.tools.build:gradle:3.2.1 > com.android.tools.build.jetifier:jetifier-core:1.0.0-alpha10
         project :@react-native-community_async-storage > com.android.tools.build:gradle:3.2.1 > com.android.tools.build.jetifier:jetifier-processor:1.0.0-alpha10
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.2.71.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.2.71.
         > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by tido64** [comment]
Hi, @anubhavnandan. Could you try again? Looks like you had a network failure and Gradle couldn't download the POMs you needed.

**Comment by Krizzu** [comment]
Closing this, as it's not Async Storage related.
